"""
Django settings for campus_security_api project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

from campus_security_api.config import EnvironmentVariables

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-3i@5n%!==p%kuaohft@yg(#w0b@@vrtj#(n6i^hrel*a0-c&5m"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "corsheaders",
    "rest_framework",
    "drf_spectacular",

    "api",
    "appdata",
    "api.system_administration",
    "api.incident_reporting",
    "api.chat"
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    "campus_security_api.middlewares.ContextUserMiddleware",
    "campus_security_api.middlewares.RequestMiddleware",
]

ROOT_URLCONF = "campus_security_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "campus_security_api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


#################################### Rest Framework Settings ####################################
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.system_administration.auth.authentication.JWTAuthentication',
    ]
}
#################################### End of Rest Framework Settings ####################################


#################################### Authentication Settings ####################################
AUTH_USER_MODEL = "appdata.User"
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'api.system_administration.auth.backends.UsernameEmailBackend'
]
#################################### End of Authentication Settings ####################################


#################################### JWT Settings ####################################
JWT_SECRET_KEY = EnvironmentVariables.JWT_SECRET_KEY
JWT_ALGORITHM = EnvironmentVariables.JWT_ALGORITHM
JWT_ACCESS_TOKEN_LIFETIME = timedelta(hours=EnvironmentVariables.JWT_ACCESS_TOKEN_LIFETIME)
JWT_REFRESH_TOKEN_LIFETIME = timedelta(hours=EnvironmentVariables.JWT_REFRESH_TOKEN_LIFETIME)
#################################### End of JWT Settings ####################################


#################################### DRF Spectacular Settings ####################################
SPECTACULAR_SETTINGS = {
    'TITLE': 'Campus Security API',
    'DESCRIPTION': 'Campus Security API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}
#################################### End of DRF Spectacular Setting ####################################


#################################### CORS Settings ####################################
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:8080",
    "http://127.0.0.1:5500",
    "http://127.0.0.1",
    "http://localhost:5500",
    "http://localhost:5173",
    "https://campussecurityapi.onrender.com",
    "https://campussecuritybackend.onrender.com",
]
#################################### End of CORS Settings ####################################


#################################### URL and Asset Directory Configuration ####################################
MEDIA_URL = '/media/'

ASSETS_DIR = os.path.join(BASE_DIR, 'site/assets')
MEDIA_ROOT = os.path.join(ASSETS_DIR, 'media/')
STATIC_ROOT = os.path.join(ASSETS_DIR, 'static/')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

USER_ACCOUNT_FILES_DIR_ROOT = 'account/'
SYSTEM_FILES_DIR_ROOT = 'system/'
#################################### End of URL and Asset Directory Configuration ####################################


#################################### Email Settings ####################################
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = EnvironmentVariables.EMAIL_HOST
EMAIL_USE_TLS = EnvironmentVariables.EMAIL_USE_TLS
EMAIL_PORT = EnvironmentVariables.EMAIL_PORT
EMAIL_HOST_USER = EnvironmentVariables.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = EnvironmentVariables.EMAIL_HOST_PASSWORD
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_DISPLAY_NAME = 'Campus Security Application'
EMAIL_SENDER = f'{EMAIL_DISPLAY_NAME} <{EMAIL_HOST_USER}>'
#################################### End of Email Setting ####################################


PASSWORD_RESET_URL = EnvironmentVariables.PASSWORD_RESET_URL
