# Generated by Django 5.2.1 on 2025-05-28 17:13

from django.db import migrations

from appdata.seeds.seeder import Seeder


class Migration(migrations.Migration):

    dependencies = [
        ("appdata", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(Seeder.insert_default001_roles),
        migrations.RunPython(Seeder.insert_default002_system_user),
        migrations.RunPython(Seeder.insert_default003_incident_category),
    ]
