# Generated by Django 5.2.1 on 2025-05-30 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appdata", "0002_auto_20250530_2004"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="incidentvote",
            name="unique_incident_vote",
        ),
        migrations.RemoveField(
            model_name="incidentvote",
            name="voter",
        ),
        migrations.AlterField(
            model_name="commentparticipant",
            name="id",
            field=models.CharField(
                default=uuid.UUID("8efd82f8-019a-48ff-b1d4-737f9fdf354a"),
                max_length=64,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="incidentvote",
            name="created_by_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incident_votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="incidentvote",
            constraint=models.UniqueConstraint(
                fields=("incident", "created_by_user"), name="unique_incident_vote"
            ),
        ),
    ]
